"""Initial import

Revision ID: 1266567cc97f
Revises: 3b5854d25914
Create Date: 2015-11-17 00:01:03.441237

"""

# revision identifiers, used by Alembic.
revision = '1266567cc97f'
down_revision = '3b5854d25914'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table, column
from sqlalchemy import String, Integer, Date, PickleType, Text, Boolean

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('core_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('admin', sa.Boolean(), nullable=False),
    sa.Column('power', sa.Boolean(), nullable=False),
    sa.Column('user', sa.Boolean(), nullable=False),
    sa.Column('guest', sa.Boolean(), nullable=False),
    sa.Column('banned', sa.Boolean(), nullable=False),
    sa.Column('mod_edituser', sa.Boolean(), nullable=False),
    sa.Column('mod_banuser', sa.Boolean(), nullable=False),
    sa.Column('editpost', sa.Boolean(), nullable=False),
    sa.Column('deletepost', sa.Boolean(), nullable=False),
    sa.Column('deletetopic', sa.Boolean(), nullable=False),
    sa.Column('posttopic', sa.Boolean(), nullable=False),
    sa.Column('postreply', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('core_settings',
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('value', sa.PickleType(), nullable=False),
    sa.Column('settinggroup', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('value_type', sa.String(length=20), nullable=False),
    sa.Column('extra', sa.PickleType(), nullable=True),
    sa.ForeignKeyConstraint(['settinggroup'], ['core_settings_group.key'], name='fk_settings_group', use_alter=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('core_settings_group',
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('core_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('password', sa.String(length=120), nullable=False),
    sa.Column('date_joined', sa.DateTime(), nullable=True),
    sa.Column('lastseen', sa.DateTime(), nullable=True),
    sa.Column('birthday', sa.DateTime(), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('website', sa.String(length=200), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('signature', sa.Text(), nullable=True),
    sa.Column('avatar', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('theme', sa.String(length=15), nullable=True),
    sa.Column('language', sa.String(length=15), nullable=True),
    sa.Column('primary_group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['primary_group_id'], ['core_groups.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('core_groups_users',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['core_groups.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['core_users.id'], )
    )
    ### end Alembic commands ###

    core_groups = table('core_groups',
        column('name', String),
        column('description', Text),
        column('admin', Boolean),
        column('power', Boolean),
        column('user', Boolean),
        column('banned', Boolean),
        column('guest', Boolean),
        column('editpost', Boolean),
        column('deletepost', Boolean),
        column('deletetopic', Boolean),
        column('posttopic', Boolean),
        column('postreply', Boolean),
        column('mod_edituser', Boolean),
        column('mod_banuser', Boolean),
    )
    op.bulk_insert(core_groups,
        [
            {'name':'Administrator',
                'description': 'The Administrator Group',
                'admin': True,
                'power': False,
                'user': False,
                'banned': False,
                'guest': False,
                'editpost': True,
                'deletepost': True,
                'deletetopic': True,
                'posttopic': True,
                'postreply': True,
                'mod_edituser': True,
                'mod_banuser': True,
            },
            {'name':'Power',
                'description': 'The User with Power Group',
                'admin': False,
                'power': True,
                'user': False,
                'banned': False,
                'guest': False,
                'editpost': True,
                'deletepost': True,
                'deletetopic': True,
                'posttopic': True,
                'postreply': True,
                'mod_edituser': True,
                'mod_banuser': True,
            },
            {'name':'User',
                'description': 'The User Group',
                'admin': False,
                'power': False,
                'user': True,
                'banned': False,
                'guest': False,
                'editpost': False,
                'deletepost': False,
                'deletetopic': False,
                'posttopic': True,
                'postreply': True,
                'mod_edituser': False,
                'mod_banuser': False,
            },
            {'name':'Banned',
                'description': 'The Banned Group',
                'admin': False,
                'power': False,
                'user': False,
                'banned': True,
                'guest': False,
                'editpost': False,
                'deletepost': False,
                'deletetopic': False,
                'posttopic': False,
                'postreply': False,
                'mod_edituser': False,
                'mod_banuser': False,
            },
            {'name':'Guest',
                'description': 'The Guest Group',
                'admin': False,
                'power': False,
                'user': False,
                'banned': False,
                'guest': True,
                'editpost': False,
                'deletepost': False,
                'deletetopic': False,
                'posttopic': False,
                'postreply': False,
                'mod_edituser': False,
                'mod_banuser': False,
            }
        ]
    )

    core_settings_group = table('core_settings_group',
        column('key', String),
        column('name', String),
        column('description', Text),
    )
    op.bulk_insert(core_settings_group,
        [
            {'key':'general', 'name':'General Settings', 'description':'General Settings for janitoo.'},
            {'key':'appearance', 'name':'Appearance Settings', 'description':'Change the theme and language for your forum.'},
        ]
    )

    core_settings = table('core_settings',
        column('key', String),
        column('name', String),
        column('description', Text),
        column('value', PickleType),
        column('value_type', String),
        column('settinggroup', String),
        column('extra', PickleType)
    )
    op.bulk_insert(core_settings,
        [
            {'key':'project_title', 'name':'Project title', 'description':'The title of the project.','value_type':'string', 'value':'Janitoo', 'extra':None, 'settinggroup':"general"},
            {'key':'project_subtitle', 'name':'Project subtitle', 'description':'A short description of the project.','value_type':'string', 'value':'Janitoo', 'extra':None, 'settinggroup':"general"},
            {'key':'posts_per_page', 'name':'Project title', 'description':'Number of posts displayed per page.','value_type':'integer', 'value':10, 'extra':{'min': 5}, 'settinggroup':"general"},
            {'key':'topics_per_page', 'name':'Project title', 'description':'Number of topics displayed per page.','value_type':'integer', 'value':10, 'extra':{'min': 5}, 'settinggroup':"general"},
            {'key':'users_per_page', 'name':'Project title', 'description':'Number of users displayed per page.','value_type':'integer', 'value':10, 'extra':{'min': 5}, 'settinggroup':"general"},

            {'key':'default_theme', 'name':'Default Theme', 'description':'Change the default theme for your forum.','value_type':'select', 'value':'admin', 'extra':{'choices': [('admin','admin'),('bootstrap3','bootstrap3'),('bootstrap2','bootstrap2')]}, 'settinggroup':"appearance"},
            {'key':'default_language', 'name':'Default Language', 'description':'Change the default language for your forum.','value_type':'string', 'value':'en', 'extra':{'choices': [('en','English')]}, 'settinggroup':"appearance"},
        ]
    )



def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('core_groups_users')
    op.drop_table('core_users')
    op.drop_table('core_settings_group')
    op.drop_table('core_settings')
    op.drop_table('core_groups')
    ### end Alembic commands ###
